services:
  - type: web
    name: document-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: TOGETHER_LLM_MODEL
        value: mistralai/Mixtral-8x7B-Instruct-v0.1
