services:
  - type: web
    name: extract-fields-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: TOGETHER_LLM_MODEL
        value: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
    plan: free
